title: 'Government of Singapore'
title-abbreviated: 'Engineer What''s Next Team'
description: Description
url: 'https://www.engineerwhatsnext.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
resources_name: resource-room
google_analytics: UA-73732262-1
favicon: /images/favicon-logo.ico
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
staging: https://ewn-staging.netlify.app
prod: https://ewn-production.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
colors:
  primary-color: '#f65819'
  secondary-color: '#f65819'
  media-colors:
    - title: media-color-one
      color: '#49759a'
    - title: media-color-two
      color: '#744d9f'
    - title: media-color-three
      color: '#00838f'
    - title: media-color-four
      color: '#00838f'
    - title: media-color-five
      color: '#00838f'
