facebook-pixel: "1120435148785475"
title: CTRL Your Future, SHIFT Your Perspective
title-abbreviated: STE What's Next Team
description: Ready to join our STE movement? Say goodbye to stereotypes and
  hello to endless opportunities in the world of science, tech and engineering.
url: https://www.ctrlshift.gov.sg
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
resources_name: newsroom
google_analytics: UA-73732262-1
favicon: /images/site settings/ctrlshiftfavicon.png
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
staging: https://staging.d24wnuuan09ldp.amplifyapp.com/
prod: https://master.d24wnuuan09ldp.amplifyapp.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
colors:
  primary-color: "#0037cc"
  secondary-color: "#0037cc"
  media-colors:
    - title: media-color-one
      color: "#75d200"
    - title: media-color-two
      color: "#000000"
    - title: media-color-three
      color: "#0037cc"
    - title: media-color-four
      color: "#00c5e4"
    - title: media-color-five
      color: "#ffffff"
shareicon: /images/site settings/social thumbnail.png
is_government: false
linkedin-insights: ""
google_analytics_ga4: "376868086"
